[package]
name = "haven-db"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
haven-domain = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
async-trait = "0.1.92"

[lints]
workspace=true
