services:
  db:
    image: postgres
    container_name: haven-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
