-- schema.sql
CREATE TABLE IF NOT EXISTS "User" (
  "id" VARCHAR(36) PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "username" TEXT,
  "name" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Post" (
  "id" VARCHAR(36) PRIMARY KEY,
  "title" TEXT NOT NULL,
  "content" TEXT,
  "authorId" VARCHAR(36) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Account" (
  "id" VARCHAR(36) PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Session" (
  "id" VARCHAR(36) PRIMARY KEY,
  "accountId" VARCHAR(36) NOT NULL,
  "token" TEXT UNIQUE NOT NULL,
  "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "userAgent" TEXT,
  "ipAddress" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MagicLink" (
  "id" VARCHAR(36) PRIMARY KEY,
  "email" TEXT NOT NULL,
  "token" TEXT UNIQUE NOT NULL,
  "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "usedAt" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "OAuthCredential" (
  "id" VARCHAR(36) PRIMARY KEY,
  "accountId" VARCHAR(36) NOT NULL,
  "provider" TEXT NOT NULL,
  "providerUserId" TEXT NOT NULL,
  "accessToken" TEXT NOT NULL,
  "refreshToken" TEXT,
  "tokenExpiresAt" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "OAuthCredential_provider_providerUserId_key" ON "OAuthCredential"("provider", "providerUserId");

CREATE TABLE IF NOT EXISTS "AccountPlatformLink" (
  "id" VARCHAR(36) PRIMARY KEY,
  "accountId" VARCHAR(36) NOT NULL,
  "platformUserId" TEXT NOT NULL,
  "platform" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "account_platform_link_unique" ON "AccountPlatformLink"("accountId", "platform");
