// ─── Scenario 02: Normal (500 RPS) ───────────────────────────────────────────
// Purpose : Verify Haven meets the core performance contract at normal load.
// Load    : 500 RPS sustained for 5 minutes.
// Focus   : 60% public reads, 30% auth reads, 10% writes (with correctness check).
// Run     : k6 run apps/api/load-tests/k6/scenarios/02-normal.js
// ─────────────────────────────────────────────────────────────────────────────
import http from 'k6/http';
import { sleep } from 'k6';
import { CONTRACT } from '../lib/config.js';
import { BASE_URL, AUTH_HEADERS, TEST_USER_ID, TEST_OFFER_ID } from '../lib/config.js';
import { checkResponse } from '../lib/helpers.js';
import { verifyWrite, correctnessRate } from '../lib/correctness.js';

export const options = {
  scenarios: {
    normal: {
      executor: 'constant-arrival-rate',
      rate: CONTRACT.normal.rps,
      timeUnit: '1s',
      duration: '5m',
      preAllocatedVUs: 150, // Enough VUs to sustain 500 RPS assuming < 300ms latency
      maxVUs: 500,
    },
  },
  thresholds: {
    http_req_duration: [
      `p(95)<${CONTRACT.normal.p95}`,
      `p(99)<${CONTRACT.normal.p99}`
    ],
    http_req_failed:     [`rate<${CONTRACT.normal.errorPct}`],
    haven_error_rate:    [`rate<${CONTRACT.normal.errorPct}`],
    haven_check_failure: [`rate<${CONTRACT.normal.errorPct}`],
    haven_correctness:   ['rate>0.999'], // Correctness should be 100% ideally
  },
};

export default function () {
  const pick = Math.random();
  let res;
  let label;

  if (pick < 0.60) {
    if (Math.random() < 0.5) {
      res = http.get(`${BASE_URL}/users?limit=50`);
      label = 'list-users';
    } else {
      res = http.get(`${BASE_URL}/offers/user/${TEST_USER_ID}?limit=50`);
      label = 'offers-by-user';
    }
  } else if (pick < 0.90) {
    if (Math.random() < 0.5) {
      res = http.get(`${BASE_URL}/auth/me`, { headers: AUTH_HEADERS });
      label = 'auth-me';
    } else {
      res = http.get(`${BASE_URL}/orders/me`, { headers: AUTH_HEADERS });
      label = 'orders-me';
    }
  } else {
    // Write path — with deep correctness check
    const payload = {
      title: `Load Test Offer ${Math.random().toString(36).substring(7)}`,
      description: "Auto-generated by k6 normal load test",
      price: Math.floor(Math.random() * 10000),
      currency: "USD",
      offerType: "PRODUCT",
      images: []
    };
    
    const isCorrect = verifyWrite(BASE_URL, AUTH_HEADERS, payload);
    correctnessRate.add(isCorrect);
    
    // We don't record latency on verifyWrite via checkResponse because verifyWrite
    // makes 2 sequential HTTP calls. The individual HTTP calls are already captured 
    // by k6 natively.
    sleep(0.5);
    return;
  }

  const expectedStatus = label.includes('create') ? 201 : 200;
  checkResponse(res, label, expectedStatus);
  sleep(0.5); // Think time
}
