// ─── Scenario 05: Soak Test (500 RPS × 30 minutes) ───────────────────────────
// Purpose : Detect memory leaks, resource accumulation, and latency drift.
// Load    : 500 RPS sustained for 30 minutes.
// Focus   : Monotonically growing RSS, or p95 creeping up over time.
// Run     : (Must run system-watch.sh alongside to capture RSS/CPU)
//           k6 run apps/api/load-tests/k6/scenarios/05-soak.js
// ─────────────────────────────────────────────────────────────────────────────
import http from 'k6/http';
import { sleep } from 'k6';
import { Trend } from 'k6/metrics';
import { CONTRACT } from '../lib/config.js';
import { BASE_URL, AUTH_HEADERS, TEST_USER_ID } from '../lib/config.js';
import { checkResponse } from '../lib/helpers.js';

// Custom trend to monitor latency drift across the entire 30m run
const soakLatencyBucket = new Trend('soak_latency_ms', true);

export const options = {
  scenarios: {
    soak: {
      executor: 'constant-arrival-rate',
      rate: CONTRACT.soak.rps,
      timeUnit: '1s',
      duration: `${CONTRACT.soak.durationMin}m`,
      preAllocatedVUs: 150,
      maxVUs: 600,
    },
  },
  thresholds: {
    http_req_duration: [
      `p(95)<${CONTRACT.soak.p95}`,
      `p(99)<${CONTRACT.soak.p99}`
    ],
    http_req_failed:     [`rate<${CONTRACT.soak.errorPct}`],
    haven_error_rate:    [`rate<${CONTRACT.soak.errorPct}`],
    soak_latency_ms:     [`p(95)<${CONTRACT.soak.p95}`],
  },
};

export function setup() {
  console.log('▶ Make sure system-watch.sh is running in the background!');
  console.log('  ./apps/api/load-tests/monitor/system-watch.sh &');
  return { startedAt: Date.now() };
}

export default function () {
  const pick = Math.random();
  let res;
  let label;

  if (pick < 0.60) {
    if (Math.random() < 0.5) {
      res = http.get(`${BASE_URL}/users?limit=50`);
      label = 'list-users';
    } else {
      res = http.get(`${BASE_URL}/offers/user/${TEST_USER_ID}?limit=50`);
      label = 'offers-by-user';
    }
  } else if (pick < 0.90) {
    if (Math.random() < 0.5) {
      res = http.get(`${BASE_URL}/auth/me`, { headers: AUTH_HEADERS });
      label = 'auth-me';
    } else {
      res = http.get(`${BASE_URL}/orders/me`, { headers: AUTH_HEADERS });
      label = 'orders-me';
    }
  } else {
    // Normal write (no deep correctness check during soak to avoid RPS skew)
    const payload = {
      title: `Load Test Offer ${Math.random().toString(36).substring(7)}`,
      description: "Auto-generated by k6 soak test",
      price: Math.floor(Math.random() * 10000),
      currency: "USD",
      offerType: "PRODUCT",
      images: []
    };
    res = http.post(`${BASE_URL}/offers`, JSON.stringify(payload), { headers: AUTH_HEADERS });
    label = 'create-offer';
  }

  const expectedStatus = label === 'create-offer' ? 201 : 200;
  const ok = checkResponse(res, label, expectedStatus);
  
  if (ok && res.timings) {
    soakLatencyBucket.add(res.timings.duration);
  }
  
  sleep(0.5);
}
