#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] Running pre-commit checks..."

echo "-> Type Checking (API)..."
bun run typecheck

echo "-> Linting & Formatting staged files..."
bunx lint-staged
