import { db } from '../../prisma/db';
import type { IUserRepository } from '../domain/user.repository';
import type { User, CreateUserData, UpdateUserData } from '../domain/user.entity';
import type { Char } from '@prisma/orm-postgres/target/codec-types';

/**
 * Prisma 8 implementation of IUserRepository.
 * This is the only file in the user feature that imports from the ORM.
 *
 * Note: Prisma 8 types UUIDs as Char<36> (branded). We cast string ↔ Char<36>
 * at the infrastructure boundary — this is intentional and safe because
 * randomUUIDv7() always produces a 36-char RFC 4122 string.
 */

function asId(id: string): Char<36> {
  return id as unknown as Char<36>;
}

export class PrismaUserRepository implements IUserRepository {
  async findById(id: string): Promise<User | null> {
    const row = await db.orm.public.User.first({ id: asId(id) });
    return row ? this.toEntity(row) : null;
  }

  async findByEmail(email: string): Promise<User | null> {
    const row = await db.orm.public.User
      .where((u) => u.email.eq(email))
      .first();
    return row ? this.toEntity(row) : null;
  }

  async findAll(): Promise<User[]> {
    const rows = await db.orm.public.User
      .orderBy((u) => u.createdAt.desc())
      .all();
    return rows.map((r) => this.toEntity(r));
  }

  async create(data: CreateUserData): Promise<User> {
    // id, createdAt, updatedAt are auto-generated by the Prisma 8 ORM.
    const row = await db.orm.public.User.create({
      email: data.email,
      username: data.username ?? null,
      name: data.name ?? null,
    });
    return this.toEntity(row);
  }

  async update(id: string, data: UpdateUserData): Promise<User> {
    const row = await db.orm.public.User
      .where({ id: asId(id) })
      .update(data);
    // The use case already verified the user exists before calling update().
    // If row is null here, it means a race condition removed the row.
    if (!row) throw new Error(`User ${id} disappeared during update`);
    return this.toEntity(row);
  }

  async delete(id: string): Promise<void> {
    await db.orm.public.User.where({ id: asId(id) }).delete();
  }

  /** Map the ORM row (Char<36> ids, branded types) to the plain domain entity. */
  private toEntity(row: {
    id: Char<36>;
    email: string;
    username: string | null;
    name: string | null;
    createdAt: string;
    updatedAt: string;
  }): User {
    return {
      id: row.id as unknown as string,
      email: row.email,
      username: row.username,
      name: row.name,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
  }
}
